config/routes.rb
Rails.application.routes.draw do
  
  #Auth routes
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :registrations => "user/registrations" }
  
  #Friend list page
  get 'my_friends', to: 'users#my_friends'
  
  get 'connect', to: 'users#index'
  
  #User profile
  get 'my_profile', to: 'users#my_profile'
  
  #Resource
  resources :users
  resources :friendships
  
  resources :conversations do
    resources :messages
  end
  
  # root => if user is authenticated
   authenticated :user do
    root 'users#my_profile'
  end
  
  # root => if user is not authenticated
  unauthenticated :user do
    devise_scope :user do
      get "/" => "welcome#index"
    end
  end
  
  #Friendships
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
  get 'add_friend', to: 'users#add_friend'
  
  #About page
  get 'company', to: 'welcome#about'
  
end

app/views/friends/_lookup.html.erb
<div id="friend-lookup">
  <%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
  <div class="form-group row no-padding text-center col-sm-12">
    <div class="col-sm-offset-3 col-sm-4">
      <%= text_field_tag :search_param, params[:search_param], 
                                  placeholder: "first name, last name or email", autofocus: true,
                                  class: 'form-control search-box input-sm' %>
    </div>
    <div class="col-sm-2">
      <%= button_tag(type: :submit, class: "btn btn-sm btn-success") do %>
        <i class="fa fa-search"></i> Look up a friend
      <% end %>
    </div>
  </div>
  <% end %>
  <%= render 'layouts/spinner' %>
  <% if @users %>
    <% if @users.size > 0 %>
        <div id="friend-lookup-results" class="well results-block col-sm-12">
          <table class="search-results-table col-sm-12">
            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td><strong>Name:</strong> <%= user.full_name %></td>
                <td><strong>Email:</strong> <%= user.email %></td>
                <td><strong>Profile:</strong> <%= link_to "View Profile", user_path(user),
                                                          class: "btn btn-sm btn-success" %>
                  <% if current_user.not_friends_with?(user.id) %>
                    <%= link_to "Add as my friend", add_friend_path(user: current_user, friend: user),
                                                      class: "btn btn-sm btn-success", method: :post %>
                  <% else %>
                    <span class="label label-primary">
                      You are friends
                    </span>
                  <% end %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
    <% else %>
    <div class="well col-sm-12">
      <h3 align="center">No people match this search criteria</h3>
    </div>
    <% end %>
  <% end %>
  <div id="friend-lookup-errors"></div>
</div>