config/routes.rb
Rails.application.routes.draw do
  
  #Auth routes
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :registrations => "user/registrations" }
  
  #Friend list page
  get 'my_friends', to: 'users#my_friends'
  
  get 'connect', to: 'users#index'
  
  #User profile
  get 'my_profile', to: 'users#my_profile'
  
  #Resource
  resources :users
  resources :friendships
  
  resources :conversations do
    resources :messages
  end
  
  # root => if user is authenticated
   authenticated :user do
    root 'users#my_profile'
  end
  
  # root => if user is not authenticated
  unauthenticated :user do
    devise_scope :user do
      get "/" => "welcome#index"
    end
  end
  
  #Friendships
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
  get 'add_friend', to: 'users#add_friend'
  
  #About page
  get 'company', to: 'welcome#about'
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]
  
  has_many :conversations, :foreign_key => :sender_id
  has_many :friendships
  has_many :friends, through: :friendships
  
  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end
  
    def not_friends_with?(friend_id)
        friendships.where(friend_id: friend_id).count < 1
    end
    
    def except_current_user(users)
        users.reject {|user| user.id == self.id}
    end
 
    def self.search(param)
        return User.none if param.blank?
        param.strip!
        param.downcase!
        (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    end
    
    def self.first_name_matches(param)
        matches('first_name', param)
    end
    
    def self.last_name_matches(param)
        matches('last_name', param)
    end
    
    def self.email_matches(param)
        matches('email', param)
    end
    
    def self.matches(field_name, param)
        where("lower(#{field_name}) like ?", "%#{param}%")
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
    def index
      
    end
    
    def show
        @user = User.find(params[:id])
    end
    
    
    def my_friends
        @friendships = current_user.friends
        @users = User.where.not("id = ?",current_user.id).order("created_at DESC")
        @conversations = Conversation.involving(current_user).order("created_at DESC")
        
        # @users = User.where.not current_user.id
        # @conversations = Conversation.involving(current_user)
    end

    def my_profile
        
    end
    
    def search
        @users = User.search(params[:search_param])
        
        if @users
          @users = current_user.except_current_user(@users)
          render partial: "friends/lookup"
        else
          render status: :not_found, nothing: true
        end
    end
  
      def add_friend
        @friend = User.find(params[:friend])
        current_user.friendships.build(friend_id: @friend.id)
        
        if current_user.save
          redirect_to my_friends_path, notice: "Friend was successfully added"
        else
          redirect_to my_friends_path, flash[:error] = "There was an error with adding user as friend"
        end
      end
    
end

app/views/users/index.html.erb
<div class="container-fluid">
  <%= render 'layouts/profile_side_bar' %>
    
  <div class="col-xs-9 col-xs-offset-3 col-md-10 col-md-offset-2 ck-content-profile">
  <div class="panel panel-default devise-bs">
    <div class="panel-heading">
      <h2 align="center">Search for friends</h2>
          <div class="panel-body">
            <%= render 'friends/lookup' %>
            <a tabindex="0" class="btn btn-sm btn-info ck-hint" role="button" data-toggle="popover" data-trigger="focus" title="Looking for new friends?" data-content="Try searching '@' and meet new people!">hint</a>
          </div>
      </div>
  </div>
</div> 
</div>

app/views/users/my_friends.html.erb
<div class="container-fluid">
  
  <%= render 'layouts/profile_side_bar' %>
  
  <% if @friendships.size > 0 %>
  <div class="row">
      <!--FIRST PANEL-->
      <!--User has friends added-->
      <div class="col-xs-9 col-xs-offset-3 col-md-10 col-md-offset-2 ck-content-profile">
      <div class="panel panel-default devise-bs">
        <div class="panel-heading">
          <h2 align="center">My Friends</h2>
          <%= link_to "Add New Friend", connect_path, class: "btn btn-primary btn-sm" %>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-2">
              <h4 class="ck-heading text-center">Name</h4>
              <hr/>
            </div>
            <div class="col-xs-4">
              <h4 class="ck-heading text-center">Email</h4>
              <hr/>
            </div>
            <div class="col-xs-6">
               <h4 class="ck-heading text-center">Actions</h4>
               <hr/>
            </div>
          </div>
          <div class="row">
          <!--This will create 3 column tabular data row-->
          <% @friendships.each do |friend| %>
            <!--User name and image-->
            <div class="col-xs-2 ck-columns">
               <!--<li class="round">image</li>-->
               <%= friend.full_name %>
            </div>
            <!--User email-->
            <div class="col-xs-4 ck-columns">
              <%= friend.email %>
            </div>
            <!--User options-->
            <div class="col-xs-6 ck-columns">
              <%= link_to "View Profile", user_path(friend), class: "btn btn-primary btn-xs" %>
              <%= link_to 'Remove Friend', friendship_path(friend), :method => :delete, 
                          :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-xs btn-danger' %>
              <%= link_to "Send Message", "#", class: "btn btn-success btn-xs start-conversation",
                              "data-sid" => current_user.id, "data-rip" => friend.id %>
            </div>
          <% end %>
          <hr>
          <!--/. logic-->
          </div>
        </div>
      </div>
      <!-- /. first panel-->
      
      <!--SECOND PANEL-->
      <!--User has no friends added-->
    <% else %>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 ck-content-profile">
        <div class="panel panel-default devise-bs">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-12">
              <h2 align="center">Ohh...</h2>
            </div>
          </div>
        </div>
        
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-12">
              <p align="center" class="lead">You don't have any friends yet. Why don't you add some?</p>
              <%= render 'friends/lookup' %>
              <a tabindex="0" class="btn btn-sm btn-info ck-hint" role="button" data-toggle="popover" data-trigger="focus" title="Looking for new friends?" data-content="Try searching '@' and meet new people!">hint</a>
            </div>
          </div>
        </div>
      </div>
      <!--/. second panel-->
      </div>
      
    <% end %>
    <!--/. logic-->
    </div>
    
  </div>
  <!--row-->
  
  </div>
<!--/. container-->


  

app/views/users/my_profile.html.erb
<div class="container-fluid">
  <div class="row">
    
    <%= render 'layouts/profile_side_bar' %>
    
    <!--Content-->
    <div class="col-xs-9 col-xs-offset-3 col-md-10 col-md-offset-2 ck-content-profile">
      <div class="panel panel-default devise-bs">
        <div class="panel-heading">
          <h1 class="page-header text-center">My profile</h1>
            <div class="row ck-profile-images ">
              <div class="col-xs-6 col-sm-3 ck-profile-image">
                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                <h4 class="ck-usernames"><%= current_user.full_name || current_user.name %></h4>
              </div>
              <hr class="divider ck-dividers"></hr>
              <div class="col-xs-6 col-sm-9 ck-userdetails">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aspernatur, sunt, adipisci, saepe odit quia consectetur ex reiciendis numquam natus omnis sed tenetur rerum delectus incidunt amet veritatis nobis impedit nostrum.</p>
              </div>
            </div>
        </div>
        <div class="panel-body">
          <div class="row">
          <!--social Icon -->
            <div class="col-xs-8 ck-columns ck-social">
              <%= link_to "Add social accounts", edit_user_registration_path, class: "btn btn-default" %> 
              <br/>
              <br/>
              <% if current_user.twitter.present? %>
              <li class="list-unstyled"><%=link_to current_user.twitter do %>
                    <i class="fa fa-twitter ck-tooltips"></i>
                  <% end %>
              </li>
              <% end %>
              <% if current_user.gmail.present? %>
              <li class="list-unstyled"><%=link_to current_user.gmail do %>
                    <i class="fa fa-google ck-tooltips"></i>
                  <% end %>
              </li>
              <% end %>
              <% if current_user.github.present? %>
              <li class="list-unstyled"><%=link_to current_user.github do %>
                    <i class="fa fa-github ck-tooltips"></i>
                  <% end %>
              </li>
              <% end %>
              <% if current_user.facebook.present? %>
              <li class="list-unstyled"><%=link_to current_user.facebook do %>
                    <i class="fa fa-facebook-official ck-tooltips"></i>
                  <% end %>
              </li>
              <% end %>
            </div>
            <!--button with tooltips-->
            <div class="col-xs-4  ck-columns">
              <%= link_to "View Profile As", user_path(current_user), class: "btn btn-info ck-links"  %>
                  <span><i class="fa fa-2x fa-question-circle ck-tooltips" data-toggle="tooltip" data-placement="top" title="Profile view as other user"></i></span>
              
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-9 col-xs-offset-2 col-md-10 col-md-offset-1 ck-content-profile">
      <div class="panel panel-default devise-bs">
      <div class="panel-heading">
          <h1 class="page-header"><%= @user.full_name %>'s profile</h1>
            <div class="row ck-profile-images">
              <div class="col-xs-6 col-sm-3 ck-profile-image">
                <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
              </div>
            </div>
        </div>
        <div class="panel-body">
            <div class="row">
              
              <div class="col-xs-6">
                <div class="panel panel-default devise-bs">
                  <div class="panel-heading">
                    <h4 class="ck-heading ">Details</h4>
                  </div>
                  <div class="panel-body">
                    <h6><strong>First name:</strong> <%= @user.first_name %></h6>
                   <h6><strong>Last name:</strong> <%= @user.last_name %></h6>
                   <h6><strong>Email:</strong> <%= @user.email %></h6>
                  </div>
                </div>
            </div>
            
            <div class="col-xs-6">
                <div class="panel panel-default devise-bs">
                  <div class="panel-heading">
                    <h4 class="ck-heading ">About</h4>
                  </div>
                  <div class="panel-body ck-about">
                    <p>Text area where user could write a bit about him</p>
                  </div>
                </div>
            </div>
          </div>
          <div class="row">
            <div class="col-xs-3 col-xs-offset-9 ck-social">
              <h4>Social Accounts</h4>
              
              <!--Twitter social logic-->
              <% if @user.twitter.present? %>
                    <li class="list-unstyled"><%=link_to @user.twitter do %>
                          <i class="fa fa-twitter ck-tooltips"></i>
                        <% end %>
                    </li>
                  <% end %>
                  
              <!--Gmail social logic-->    
                  <% if @user.gmail.present? %>  
                    <li class="list-unstyled"><%=link_to @user.gmail do %>
                          <i class="fa fa-google ck-tooltips"></i>
                        <% end %>
                    </li>
                  <% end %> 
              <!--Github social logic-->    
              
                  <% if @user.github.present? %>  
                    <li class="list-unstyled"><%=link_to @user.github do %>
                          <i class="fa fa-github ck-tooltips"></i>
                        <% end %>
                    </li>
                    <% end %> 
                    
              <!--Facebook social logic-->      
                  <% if @user.facebook.present? %>
                    <li class="list-unstyled"><%=link_to @user.facebook do %>
                          <i class="fa fa-facebook-official ck-tooltips"></i>
                        <% end %>
                    </li>
                  <% end %>  
              </div>
          </div>
          <%= link_to "Back", my_friends_path, class: 'btn btn-primary' %>
        </div>
    </div>
  </div>
</div>
</div>