config/routes.rb
Rails.application.routes.draw do
  
  #Auth routes
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", :registrations => "user/registrations" }
  
  #Friend list page
  get 'my_friends', to: 'users#my_friends'
  
  get 'connect', to: 'users#index'
  
  #User profile
  get 'my_profile', to: 'users#my_profile'
  
  #Resource
  resources :users
  resources :friendships
  
  resources :conversations do
    resources :messages
  end
  
  # root => if user is authenticated
   authenticated :user do
    root 'users#my_profile'
  end
  
  # root => if user is not authenticated
  unauthenticated :user do
    devise_scope :user do
      get "/" => "welcome#index"
    end
  end
  
  #Friendships
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'
  get 'add_friend', to: 'users#add_friend'
  
  #About page
  get 'company', to: 'welcome#about'
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-offset-2 col-xs-8 text-center ck-social">
        <h4>Follow Us On</h4>
        <li class="list-unstyled">  <%=link_to "https://github.com/CodeKrieg" do %>
             <i class="fa fa-github ck-tooltips"></i>
           <% end %>
        </li>
        <li class="list-unstyled">  <%=link_to "https://twitter.com/CodeKrieg" do %>
             <i class="fa fa-twitter ck-tooltips"></i>
           <% end %>
        </li>
        <li class="list-unstyled">  <%=link_to "https://www.facebook.com/codekriegdev" do %>
             <i class="fa fa-facebook ck-tooltips"></i>
           <% end %>
        </li>
      </div>
    </div>
      <p class="text-muted text-center ck-footer">&copy; All Rights Reserved - CodeKrieg - <%= Time.now.year %></p>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "ChatApp", root_path, class: "navbar-brand" %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li><%= link_to "My Profile", my_profile_path %></li>
          <li><%= link_to "About", company_path %></li>
        <% else %>
          <li><%= link_to "Home", root_path  %></li>
          <li><%= link_to "About", company_path  %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="ck-badge">
             <span class="badge">
               <i class="fa fa-user fa-2x"></i>
                <%= link_to  current_user.full_name.present? ? current_user.full_name : current_user.email, my_profile_path %>
             </span>
          </li>
          <%= link_to "logout", destroy_user_session_path, method: :delete, :class => "btn btn-danger btn-md ck-button" %>
           
        <% else %>
          <%= link_to "Sign in", new_user_session_path, :class => "btn btn-success btn-md ck-button" %> 
          <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-primary btn-md ck-button" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_profile_side_bar.html.erb
<!--Sidebar-->
<div class="col-sm-3 col-md-2 ck-sidebar-profile">
  <ul class="nav nav-sidebar">
    <li><%= nav_link "My Profile", my_profile_path %></li>
    <li><%= nav_link "My Friends", my_friends_path %></li>
    <li><%= nav_link "Add New Friends", connect_path %></li>
    <li><%= link_to "Edit account", edit_user_registration_path %></li>
  </ul>
</div>
<!--/. sidebar-->

app/views/layouts/_spinner.html.erb
<div id="spinner" class="row col-md-12 text-center spinner" style="display: none;">
  <i class="fa fa-spinner fa-spin fa-2x"></i> Processing...
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content='<%= user_signed_in? ? current_user.id : "" %>' name='user-id'>
    <title><%= content_for?(:title) ? yield(:title) : "ChatApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <% unless current_page?('/users/sign_in') || current_page?('/users/sign_up') %>
      <%= render 'layouts/navigation' %>
    <% end %>
    
    <div class="container">
      <div class="row">
        <div class="col-sm-7 col-sm-offset-3 text-center">
          <%= bootstrap_flash %>
        </div>
        
        <!--SIDEBAR-->
        <!--<div class="col-lg-3">-->
          <!--<div class="well sidebar-nav">-->
            <!--<h3>Sidebar</h3>-->
            <!--<ul class="nav nav-list">-->
              <!--<li class="nav-header">Sidebar</li>-->
              <!--<li><%= link_to "Link1", "/path1"  %></li>-->
              <!--<li><%= link_to "Link2", "/path2"  %></li>-->
              <!--<li><%= link_to "Link3", "/path3"  %></li>-->
            <!--</ul>-->
          <!--</div> -->
          <!--/.well-->
        <!--</div>-->
        <!--/. sidebar-->
        
      </div>
      
       <%= yield %>
      <!--/. row-->
    </div> 
    <!-- /. container -->
    
    <% unless current_page?('/users/sign_in') || current_page?('/users/sign_up') %>
      <%= render 'layouts/footer' %>
    <% end %>
    
    <audio id="chatAudio"><source src="/sounds/notification.mp3" type="audio/mpeg"></audio>
  </body>
  
</html>